import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Article from '../components/Article';
import stay from '../components/Notes1';

export default function Home() {
  return (
    <div >
   <Head>
     <title> Create Next App</title>
     <meta name='description' content='Generated by create next app'/>
     <link rel='icon' href='/favicon.ico'/>
     
   </Head>
   <Navbar/>
   <Hero />

   </div>
  );
}
